import Icon from '../components/Icon'
import PageHero from '../components/PageHero'
import { HOSPITAL_MAPS_URL, hospitalAddress, type Language } from '../data/site'

export default function AboutPage({ language }: { language: Language }) {
  const values = [
    ['stethoscope', language === 'en' ? 'Practical medical care' : 'व्यावहारिक वैद्यकीय सेवा', language === 'en' ? 'Clear evaluation, appropriate investigations and follow-up focused on the patient’s clinical needs.' : 'रुग्णाच्या गरजांनुसार स्पष्ट तपासणी, योग्य चाचण्या व फॉलो-अप.'],
    ['shield', language === 'en' ? 'Critical-care readiness' : 'क्रिटिकल केअर तयारी', language === 'en' ? 'ICU, respiratory support and cardiac monitoring facilities for acutely ill patients.' : 'गंभीर रुग्णांसाठी ICU, श्वसन सपोर्ट व कार्डियाक मॉनिटरिंग सुविधा.'],
    ['message', language === 'en' ? 'Accessible coordination' : 'सोपे समन्वय', language === 'en' ? 'Phone and WhatsApp options for appointment coordination, timings and directions.' : 'अपॉइंटमेंट, वेळा व दिशांसाठी फोन आणि WhatsApp पर्याय.'],
  ] as const
  return <>
    <PageHero eyebrow={language === 'en' ? 'About the hospital' : 'हॉस्पिटलबद्दल'} title={language === 'en' ? 'Local care with medicine and critical-care support.' : 'मेडिसिन व क्रिटिकल केअर सुविधांसह स्थानिक आरोग्यसेवा.'} description={language === 'en' ? 'Shree Gajanan Hospital & Critical Care Center serves patients in Warud with physician-led medical care, critical-care support, anaesthesia and selected diagnostic services.' : 'श्री गजानन हॉस्पिटल अँड क्रिटिकल केअर सेंटर, वरुड येथे फिजिशियन-नेतृत्वाखालील मेडिसिन, क्रिटिकल केअर, भूल व निवडक निदान सेवा उपलब्ध आहेत.'}>
      <a href="/appointment" className="btn-primary">{language === 'en' ? 'Request Appointment' : 'अपॉइंटमेंट विनंती'}</a>
      <a href={HOSPITAL_MAPS_URL} target="_blank" rel="noreferrer" className="btn-secondary"><Icon name="map" className="mr-2 h-5 w-5"/>{language === 'en' ? 'Directions' : 'दिशा'}</a>
    </PageHero>
    <section className="section-pad bg-white"><div className="container-shell grid gap-10 lg:grid-cols-2 lg:items-center"><div className="overflow-hidden rounded-[32px] border border-hospital-line bg-hospital-bg p-8 shadow-card"><img src="/images/hospital-logo-brochure.webp" alt="Shree Gajanan Hospital logo" className="mx-auto h-56 w-full max-w-md object-contain"/></div><div><div className="eyebrow">{language === 'en' ? 'Our approach' : 'आमचा दृष्टिकोन'}</div><h2 className="section-title">{language === 'en' ? 'Care that is easy to understand and easier to access.' : 'समजण्यास सोपी आणि सहज उपलब्ध आरोग्यसेवा.'}</h2><p className="mt-5 leading-8 text-hospital-muted">{language === 'en' ? 'The website is designed to help patients understand the hospital’s core services, meet the doctors, check facilities and quickly contact the team. It does not replace an in-person medical assessment.' : 'ही वेबसाइट हॉस्पिटलच्या प्रमुख सेवा, डॉक्टर, सुविधा आणि संपर्क पर्याय समजण्यासाठी तयार केली आहे. ती प्रत्यक्ष वैद्यकीय तपासणीची जागा घेत नाही.'}</p><div className="mt-6 rounded-2xl border border-hospital-line bg-hospital-bg p-5"><div className="text-xs font-black uppercase tracking-widest text-hospital-teal">Warud</div><p className="mt-2 leading-7 text-hospital-ink">{hospitalAddress[language]}</p></div></div></div></section>
    <section className="section-pad bg-hospital-bg"><div className="container-shell"><div className="text-center"><div className="eyebrow">{language === 'en' ? 'What patients can expect' : 'रुग्ण काय अपेक्षा करू शकतात'}</div><h2 className="section-title mx-auto max-w-3xl">{language === 'en' ? 'A focused hospital experience built around access, clarity and clinical support.' : 'उपलब्धता, स्पष्टता आणि वैद्यकीय सहाय्यावर आधारित हॉस्पिटल अनुभव.'}</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{values.map(([icon,title,text]) => <div key={title} className="card p-6"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-hospital-tealSoft text-hospital-teal"><Icon name={icon as any} className="h-6 w-6"/></span><h3 className="mt-5 text-xl font-black text-hospital-navy">{title}</h3><p className="mt-3 leading-7 text-hospital-muted">{text}</p></div>)}</div></div></section>
  </>
}
